channels:
  - defaults
  - conda-forge
  - bioconda
  - Eugene_T
dependencies:
  - r-base=4.0
  - r-tidyverse
  - r-sitmo
  - r-bh
  - r-rcppeigen
  - r-r.methodss3
  - r-rcppgsl
  - r-rcpparmadillo
  - r-igraph
  - r-polyclip
  - r-tweenr
  - r-xfun
  - r-gridextra
  - bioconductor-s4vectors
  - bioconductor-biocgenerics
  - r-cluster
  - r-globaloptions
  - r-rjson
  - r-shape
  - r-dqrng
  - r-rcppprogress
  - r-irlba
  - r-rcppannoy
  - r-rspectra
  - r-fnn
  - r-r.oo
  - r-rcppziggurat
  - r-data.table
  - r-corpcor
  - r-graphlayouts
  - r-tidygraph
  - r-viridis
  - r-ggrepel
  - r-ggforce
  - r-survival
  - r-matrixstats
  - bioconductor-iranges
  - r-cairo
  - r-png
  - r-clue
  - r-getoptlong
  - r-circlize
  - r-gmp
  - r-gtools
  - r-uwot
  - r-r.utils
  - r-rtsne
  - r-rfast
  - r-reticulate
  - bioconductor-qvalue
  - r-plotly
  - r-magick
  - bioconductor-limma
  - bioconductor-lfa
  - r-ggraph
  - r-ggdendro
  - r-ggalluvial
  - r-fitdistrplus
  - r-dendextend
  - r-deldir
  - r-dbscan
  - r-cowplot
  - bioconductor-complexheatmap
  - r-clusterr
  - bioconductor-mast
  - r-tiff
  - bioconductor-biomart
#   - r-trendsceek
  - r-multinet
  - r-factominer
  - r-jackstraw
  - bioconductor-scran
  - bioconductor-mast
  
# 

  — pip=3.4
  — pandas
  — networkx
  - python-igraph
  - leidenalg
  - python-louvain
  - scikit-learn